<a href="https://colab.research.google.com/github/meryemaltintas/Math-2024-25-Winter/blob/main/Meryem_Linear_Algebra_01_Matrices_LA_Matrix_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np

# 1. Calculate the sum of matrices A and B
A1 = np.array([[1, 2], [3, 4]])
B1 = np.array([[5, 6], [7, 8]])

sum_AB = A1 + B1
print("1. Sum of A and B:\n", sum_AB)

# 2. Calculate the product of matrix A and scalar k = 1/4
A2 = np.array([[4, 2], [12, 4]])
k = 1/4

scalar_product = A2 * k
print("\n2. Product of matrix A and scalar 1/4:\n", scalar_product)

# 3. Calculate the products A * B and B * A
A3 = np.array([[3, 2], [2, 4]])
B3 = np.array([[4, 1], [6, 4]])

product_AB = np.dot(A3, B3)
product_BA = np.dot(B3, A3)

print("\n3. Product A * B:\n", product_AB)
print("\nProduct B * A:\n", product_BA)

1. Sum of A and B:
 [[ 6  8]
 [10 12]]

2. Product of matrix A and scalar 1/4:
 [[1.  0.5]
 [3.  1. ]]

3. Product A * B:
 [[24 11]
 [32 18]]

Product B * A:
 [[14 12]
 [26 28]]
