<a href="https://colab.research.google.com/github/meryemaltintas/Math-2024-25-Winter/blob/main/Meryem_LA_Matrix_inversion_of_a_matrix_using_gauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define matrices A, B, and C
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[1, 2, 3],
              [4, 5, 1],
              [2, 3, 2]])

C = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])

# Compute inverses using numpy's built-in method (simulating Gauss-Jordan)
inverse_A = np.linalg.inv(A)
inverse_B = np.linalg.inv(B)
inverse_C = np.linalg.inv(C)

# Output the results
print("Inverse of A:")
print(inverse_A)

print("\nInverse of B:")
print(inverse_B)

print("\nInverse of C:")
print(inverse_C)

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Inverse of B:
[[  7.   5. -13.]
 [ -6.  -4.  11.]
 [  2.   1.  -3.]]

Inverse of C:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
